SUPABASE_URL = "https://cnkthhflfybdmnqywvrl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNua3RoaGZsZnliZG1ucXl3dnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NTQxMzYsImV4cCI6MjA5MjMzMDEzNn0.LziWpB9FJhY6b7t63BKD7HhyrAd8K9AnulaRyKUy8mY"
